### PR TITLE
migrate import file button

### PR DESCRIPTION
**Pull request by maksklimko**
Changes:
- removed import file button on sidebar
- added new text button for importing file

### CODE REVIEW

**Comment by maksklimko** [comment]
@IldySilva sorry, I didn't see your comment on time)

**Comment by IldySilva** [comment]
You did a great job✍🏾 I'll be waiting for more contributions from you

**Comment by Rajvardhan222** [comment]
is it open?

**Comment by IldySilva** [comment]
no is not

**Pull request closed without merging**
